//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public Animal()
        {
            this.Consulta = new HashSet<Consulta>();
        }
    
        public int IdAnimal { get; set; }
        public int IdClienteFK { get; set; }
        public int IdTipoFK { get; set; }
        public int IdRacaFK { get; set; }
        public string NomeAnimal { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> Altura { get; set; }
        public string Alergico { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Raca Raca { get; set; }
        public virtual Tipo Tipo { get; set; }
        public virtual ICollection<Consulta> Consulta { get; set; }
    }
}
