//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Animal = new HashSet<Animal>();
            this.Telefone = new HashSet<Telefone>();
        }
    
        public int IdCliente { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string RG { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public string Endereco { get; set; }
        public string Whatsapp { get; set; }
    
        public virtual ICollection<Animal> Animal { get; set; }
        public virtual ICollection<Telefone> Telefone { get; set; }
    }
}
