//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public int IdConsulta { get; set; }
        public int IdVeterinarioFK { get; set; }
        public int IdAnimalFK { get; set; }
        public System.DateTime DataHora { get; set; }
        public decimal Valor { get; set; }
        public string Diagnostico { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Veterinario Veterinario { get; set; }
    }
}
