//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefone
    {
        public int IdTelefone { get; set; }
        public int IdClienteFK { get; set; }
        public string NumeroTelefone { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
