//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelefoneVeterianrio
    {
        public int IdTelefoneVeterinario { get; set; }
        public int IdVeterinarioFK { get; set; }
        public string NumeroTelefone { get; set; }
    
        public virtual Veterinario Veterinario { get; set; }
    }
}
