//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo
    {
        public Tipo()
        {
            this.Animal = new HashSet<Animal>();
        }
    
        public int IdTipo { get; set; }
        public string TipoAnimal { get; set; }
    
        public virtual ICollection<Animal> Animal { get; set; }
    }
}
